//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbrellaService.DataLevel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> TaskId { get; set; }
        public System.DateTime DatePublic { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Task Task { get; set; }
    }
}
